# Generated by Django 5.0.4 on 2024-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories_per_hundred_grams',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
